name: Build

on:
  workflow_call:
    inputs: 
      NVM_TAG:
        type: string
        required: false
        default: 4.13.2-1-jdk11-5a9ba13-a7f7fa0
        description: NVM_TAG to build
      CORE_TAG:
        type: string
        required: false
        default: 4.13.2-1-jdk11-5a9ba13
        description: CORE_TAG to build
      IMAGE_NAME:
        description: Name of image to publish to dockerhub, e.g. 'dwolla/my-image'
        type: string
        required: true
      TAG_NAME:
        description: ARG input into Dockerfile for tag (valid options are NVM_TAG, NVM_TAG_JDK8_JDK11, CORE_TAG, CORE_TAG_JDK8_JDK11)
        type: string
        required: true
      PLATFORMS:
        description: Platforms to build for (i.e. linux/arm64)
        type: string
        required: false
        default: linux/amd64,linux/arm64
    secrets: 
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  TAG: ${{ inputs[inputs.TAG_NAME] }}

jobs:
  build:
    if: ${{ inputs.TAG_NAME == 'NVM_TAG' || inputs.TAG_NAME == 'CORE_TAG' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ env.TAG }}
          TAG_NAME: ${{ inputs.TAG_NAME }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          PLATFORMS: ${{ inputs.PLATFORMS }}

  build-core-matrix:
    strategy:
      matrix:
        TAG:
          - 4.13.2-1-jdk11-5a9ba13
          - 4.13.2-1-jdk8-5a9ba13
    if: ${{ inputs.TAG_NAME == 'CORE_TAG_JDK8_JDK11' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ matrix.TAG }}
          TAG_NAME: "CORE_TAG"
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}

  build-nvm-matrix:
    strategy:
      matrix:
        TAG:
          - 4.13.2-1-jdk11-5a9ba13-a7f7fa0
          - 4.13.2-1-jdk8-5a9ba13-a7f7fa0
    if: ${{ inputs.TAG_NAME == 'NVM_TAG_JDK8_JDK11' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ matrix.TAG }}
          TAG_NAME: "NVM_TAG"
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}