name: Build

on:
  workflow_call:
    inputs: 
      NVM_TAG:
        type: string
        required: false
        default: sha-a9c907d-core-4.13.2-1-jdk11-7b03219
        description: NVM_TAG to build
      CORE_TAG:
        type: string
        required: false
        default: 4.13.2-1-jdk11-7b03219
        description: CORE_TAG to build
      BUILD_JDK_8:
        description: Whether or not to build image with JDK 8 base image as well as JDK 11.
        type: boolean
        required: false
        default: false
      IMAGE_NAME:
        description: Name of image to publish to dockerhub, e.g. 'dwolla/my-image'
        type: string
        required: true
      TAG_NAME:
        description: ARG input into Dockerfile for tag (e.g. NVM_TAG, CORE_TAG, etc.)
        type: string
        required: true
    secrets: 
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  TAG: ${{ inputs[inputs.TAG_NAME] }}

jobs:
  build:
    if: ${{ inputs.BUILD_JDK_8 }} == false
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ env.TAG }}
          TAG_NAME: ${{ inputs.TAG_NAME }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
  build-matrix:
    strategy:
      matrix:
        TAG:
          - ${{ inputs[inputs.TAG_NAME] }}
          - 4.13.2-1-jdk8-7b03219
    if: ${{ inputs.BUILD_JDK_8 }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ matrix.TAG }}
          TAG_NAME: ${{ inputs.TAG_NAME }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
